services:
  frontend:
    build:
      context: frontend
      dockerfile: Docker/development/Dockerfile
    image: recipy-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app/:/app/app/"
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./users-db/pgdata:/var/lib/postgresql/data
      - ./db-postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

