services:
  frontend:
    build:
      context: frontend
      dockerfile: Docker/development/Dockerfile
    image: recipy-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app/:/app/app/"
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./db-postgres/pgdata:/var/lib/postgresql/data
      - ./db-postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    volumes:
      - ./db-mongo/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "27018:27017"    # mapea 27018 en el host al 27017 del contenedor
