services:
  frontend:
    build:
      context: frontend
      dockerfile: Docker/development/Dockerfile
    image: recipy-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app/:/app/app/"
