services:
  # Frontend (Next.js)
  recipy-frontend:
    build:
      context: ./recipy-frontend
      dockerfile: Docker/development/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229" # Debugger
      - "9230:9230" # Debugger
    volumes:
      - ./recipy-frontend/src:/app/src
    env_file:
      - .env
    networks:
      - frontend

  # Recipe micro-service (FastAPI/Uvicorn)
  recipe-ms:
    build:
      context: ./recipe-ms
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./recipe-ms/app:/app/app
    env_file:
      - .env # <— esto carga JWT_SECRET y JWT_ALGO en recipe-ms
    depends_on:
      - recipe-db
    networks:
      - backend

  # MongoDB for recipes
  recipe-db:
    image: mongo:6
    container_name: recipe-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./recipe-db/data:/data/db
      - ./recipe-db/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "27018:27017"
    networks:
      - backend

  # PostgreSQL for user-auth
  userauth-db:
    image: postgres:17.5-alpine3.21
    container_name: userauth-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./userauth-db/data:/var/lib/postgresql/data
      - ./userauth-db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend

# PostgreSQL for userauth-tokens
  token-db:
    build:
      context: ./token-db
      dockerfile: Dockerfile
    container_name: token-db
    restart: always
    env_file:
      - .env
    environment:
      # Estas tres variables son las que usa postgres:17.5-alpine para crear la BD
      POSTGRES_USER:   ${TOKEN_DB_USER}
      POSTGRES_PASSWORD: ${TOKEN_DB_PASSWORD}
      POSTGRES_DB:     ${TOKEN_DB_NAME}
    volumes:
      - ./token-db/data:/var/lib/postgresql/data
      - ./token-db/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"
    networks:
      - backend

  # PostgREST for user-auth
  userauth-postgrest:
    image: postgrest/postgrest:v13.0.0
    container_name: userauth-postgrest
    restart: always
    env_file:
       - .env
    volumes:
      - ./userauth-postgrest/postgrest.conf:/etc/postgrest.conf:ro
      #- ./recipe-db/data:/data/db  # Persistencia de datos
      #- ./recipe-db/initdb:/docker-entrypoint-initdb.d:ro # Comando de inicialización
    
    ports:
      - "3001:3000"
    depends_on:
      - userauth-db
    networks:
      - backend

  # Custom Flask + PostgREST orchestrator
  userauth-ms:
    build:
      context: ./userauth-ms
    env_file:
      - .env     # Apunta al .env de la raíz
    ports:
      - "5000:5000"   
    depends_on:
      - userauth-postgrest
      - token-db
    networks:
      - backend

  # API Gateway (Nest + Express + HTTP-Proxy-Middleware)
  recipy-ag:
    build:
      context: ./recipy-ag
    env_file:
      - .env
    ports:
      - "3030:3030"
    depends_on:
      - userauth-ms
      - recipe-ms
    networks:
      - backend
      - frontend
  
  # Imgur MS (ASP.NET Core Web API)
  image-ms:
    build:
      context: ./image-ms
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./image-ms/uploads:/app/wwwroot/uploads
    networks:
      - backend

  # Servicio de correo asíncrono
  mail-ms:
    build:
      context: ./mail-ms
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    env_file:
      - .env      # Carga MAIL_SMTP_* y AMQP_URL
    depends_on:
      - mail-broker
    networks:
      - backend
    restart: always

  # Broker de mensajes (RabbitMQ)
  mail-broker:
    image: rabbitmq:3-management
    container_name: mail-broker
    restart: always
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      backend:
        aliases:
          - rabbitmq   # para tests de userauth-ms

volumes:
  rabbitmq_data:

networks:
  frontend:
  backend:
    driver: bridge

