apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: image-rp-lb
  name: image-rp-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-rp-lb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: image-rp-lb
    spec:
      containers:
        - image: nginx:alpine
          name: image-rp-lb
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: image-rp-lb-cm0
              readOnly: true
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: default.conf
                path: default.conf
            name: image-rp-lb-cm0
          name: image-rp-lb-cm0
