apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: image-ms
  name: image-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: image-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: image-ms
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: ludiazv/recipy-image-ms
          name: image-ms
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/wwwroot/uploads
              name: image-ms-cm0
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
      volumes:
        - configMap:
            name: image-ms-cm0
          name: image-ms-cm0
