apiVersion: v1
data:
  default.conf: |2
     # define el pool de réplicas
    upstream image_ms_pool {
      # Docker DNS balancea requests entre recipy-image-ms-1, -2, -3
      least_conn; #usar algoritmo least connections
      server recipy-image-ms-1:8080;
      server recipy-image-ms-2:8080;
      server recipy-image-ms-3:8080;
    }

    server {
      listen 80 default_server;
      server_name _;

      location / {
        proxy_pass         http://image_ms_pool;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: image-rp-lb
  name: image-rp-lb-cm0
