apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-ms-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /vol
    server: 10.166.151.242
