apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mail-ms
  name: mail-ms
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8080
  selector:
    io.kompose.service: mail-ms
