apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipe-ms
  name: recipe-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipe-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipe-ms
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: recipe-ms
          name: recipe-ms
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
