apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipe-db
  name: recipe-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipe-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipe-db
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: mongo:6
          name: recipe-db
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: recipe-db-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: recipe-db-cm1
          name: recipe-db-cm1
