apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipy-cache
  name: recipy-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipy-cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipy-cache
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: redis:7
          name: recipy-cache
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
