apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipy-frontend
  name: recipy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipy-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipy-frontend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: recipy-frontend
          name: recipy-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 9229
              protocol: TCP
            - containerPort: 9230
              protocol: TCP
      restartPolicy: Always
