apiVersion: v1
data:
  default.conf.template: |
    server {
        listen 80;

        location / {
            proxy_pass ${API_GATEWAY_URL};  # Cambia el puerto si tu servicio usa otro
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: recipy-rp
  name: recipy-rp-cm0
