apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipy-frontend
  name: recipy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipy-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipy-frontend
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: env
          image: juandvasquezp/recipy-frontend:latest
          name: recipy-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
