apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipy-rp-frontend
  name: recipy-rp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipy-rp-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: recipy-rp-frontend
    spec:
      volumes:
        - name: recipy-rp-frontend-cm0
          configMap:
            name: recipy-rp-frontend-cm0
        - name: recipy-rp-frontend-cm1
          configMap:
            name: recipy-rp-frontend-cm1
        - name: recipy-rp-frontend-cm2
          configMap:
            name: recipy-rp-frontend-cm2
        - name: recipy-rp-frontend-cm3
          configMap:
            name: recipy-rp-frontend-cm3
        - name: recipy-rp-frontend-cm4
          configMap:
            name: recipy-rp-frontend-cm4
        - name: script-volume
          emptyDir: {}

      initContainers:
        - name: copy-entrypoint
          image: busybox
          command:
            - sh
            - -c
            - cp /config/entrypoint.sh /work/entrypoint.sh && chmod +x /work/entrypoint.sh
          volumeMounts:
            - name: recipy-rp-frontend-cm1
              mountPath: /config
            - name: script-volume
              mountPath: /work

      containers:
        - name: recipy-rp-frontend
          image: nginx:alpine
          command: ["/work/entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: script-volume
              mountPath: /work
            - name: recipy-rp-frontend-cm0
              mountPath: /etc/nginx/conf.d/default.conf.template
              subPath: default.conf.template
              readOnly: true
            - name: recipy-rp-frontend-cm2
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: recipy-rp-frontend-cm3
              mountPath: /etc/ssl/certs/recipy.crt
              subPath: recipy.crt
              readOnly: true
            - name: recipy-rp-frontend-cm4
              mountPath: /etc/ssl/private/recipy.key
              subPath: recipy.key
              readOnly: true
      restartPolicy: Always
