apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: recipy-frontend
  name: recipy-frontend
spec:
  type: LoadBalancer  # <-- Esta línea es clave
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: recipy-frontend
