apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: userauth-ms
  name: userauth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userauth-ms
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert --out manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: userauth-ms
    spec:
      containers:
        - env:
            - name: PGRST_URL_LOCAL
              value: http://userauth-postgrest:3000
            - name: POSTGRES_HOST
              value: userauth-db
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - configMapRef:
                name: env
          image: fnovoas/recipy-userauth-ms:latest
          name: userauth-ms
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
